{{ if .Values.deployOLM }}
{{ if not (eq .Values.olmNamespace .Release.Namespace) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.olmOperatorNamespace }}
  {{- if .Values.annotations}}
  annotations:
  {{ .Values.annotations | toYaml | nindent 4 }}
  {{- end }}
{{ end }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: global-operators
  namespace: {{ .Values.olmOperatorNamespace }}
  {{ end }}