apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  name: vizier-deleter
  namespace: '{{ .Values.olmOperatorNamespace }}'
spec:
  template:
    metadata:
      name: vizier-deleter
    spec:
      containers:
      - env:
        - name: PL_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PL_VIZIER_NAME
          value: '{{ .Values.olmOperatorNamespace }}'
        image: gcr.io/pixie-oss/pixie-prod/operator/vizier_deleter:0.1.4
        name: delete-job
      restartPolicy: Never
      serviceAccountName: pl-deleter-service-account
      {{- with include "custom.tolerations" . }}
      tolerations:
        {{- . | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeselector }}
      nodeSelector:
        {{ .Values.nodeselector | toYaml | nindent 8 }}
      {{- end}}
